# Generated by Django 5.2.17 on 2026-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_category_owner_priority_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Overdue", "Overdue"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Overdue", "Overdue"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
